### ISSUE TITLE
Update list of packages

### ISSUE THREAD

**Issue by oxinabox** [JuliaDiff/juliadiff.github.io#8]
Forward mode:
- [ForwardDiff](https://github.com/JuliaDiff/ForwardDiff.jl)
- [ForwardDiff2](https://github.com/YingboMa//ForwardDiff2.jl)

Reverse Mode:
- [Nabla](https://github.com/invenia/Nabla.jl/)
- [Tracker](https://github.com/FluxML/Tracker.jl)
- [Yota](https://github.com/dfdx/Yota.jl)
- [Zygote](https://github.com/FluxML/Zygote.jl)
- [ReverseDiff](https://github.com/JuliaDiff/ReverseDiff.jl)
- [AutoGrad.jl](https://github.com/denizyuret/AutoGrad.jl)
- [NiLang](https://github.com/GiggleLiu/NiLang.jl) (arguably not reverse mode)

Symbolic:
- [ModelingToolKit](https://github.com/JuliaDiffEq/ModelingToolkit.jl)
- [XGrad.jl](https://github.com/dfdx/XGrad.jl)

Finite Differencing:

- [Calculus](https://github.com/JuliaMath/Calculus.jl) (please stop)
- [FiniteDifferences](https://github.com/JuliaDiff/FiniteDifferences.jl)
- [FiniteDiff](https://github.com/JuliaDiff/FiniteDiff.jl)

Rulesets:
- [ChainRules](https://github.com/JuliaDiff/ChainRulesCore.jl)
- [DiffRules](https://github.com/JuliaDiff/ChainRulesCore.jl) (soon to stop)

Sparsity Detection
- [SparseDiffTools](https://github.com/JuliaDiff/SparseDiffTools.jl)

**Comment by ChrisRackauckas** [comment]
SparsityDetection.jl is for sparsity detection. SparseDiffTools is for sparsifying forward and reverse mode.
