### ISSUE TITLE
Site is misformatted

### ISSUE THREAD

**Issue by sethaxen** [JuliaDiff/juliadiff.github.io#9]
Currently neither the LaTeX equations nor the status symbols render correctly: https://www.juliadiff.org/

**Comment by mlubin** [comment]
@sethaxen Thanks for pointing this out.

@ChrisRackauckas What do you want to do with this website? I have no plans to maintain it.

**Comment by ViralBShah** [comment]
I think it would be nice to fix the rendering and keep the website as is. Perhaps @mlubin - remove the footer at the bottom that says you maintain it? Hopefully, over time, we will get new maintainers.

@oxinabox @MikeInnes?

**Comment by mlubin** [comment]
Related to the original issue, the equations display correctly for me on the http version of the website: http://www.juliadiff.org/.

**Comment by ChrisRackauckas** [comment]
That would mean that the CSS is probably using the http link instead of the https link.

**Comment by ViralBShah** [comment]
https://github.com/JuliaDiff/juliadiff.github.io/pull/11

We should probably remove the badges, and the pkg.julialang.org needs to be replaced with juliahub.com links. I can submit those PRs if the one above gets the formatting fixed.

**Comment by ViralBShah** [comment]
Can someone give me admin access here? I can at least fix the website.

**Comment by gdalle** [comment]
Closed by #13
